[2023-01-26 14:03:45,531] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d1_script.insert_province_daily scheduled__2023-01-25T00:00:00+00:00 [queued]>
[2023-01-26 14:03:45,544] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d1_script.insert_province_daily scheduled__2023-01-25T00:00:00+00:00 [queued]>
[2023-01-26 14:03:45,545] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 14:03:45,545] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-26 14:03:45,546] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 14:03:45,562] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-01-25 00:00:00+00:00
[2023-01-26 14:03:45,568] {standard_task_runner.py:52} INFO - Started process 364 to run task
[2023-01-26 14:03:45,571] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd1_script', 'insert_province_daily', 'scheduled__2023-01-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/d1_script.py', '--cfg-path', '/tmp/tmplytc8mjm', '--error-file', '/tmp/tmpz0h8vgym']
[2023-01-26 14:03:45,572] {standard_task_runner.py:80} INFO - Job 6: Subtask insert_province_daily
[2023-01-26 14:03:45,627] {task_command.py:369} INFO - Running <TaskInstance: d1_script.insert_province_daily scheduled__2023-01-25T00:00:00+00:00 [running]> on host ec233ae30e03
[2023-01-26 14:03:45,705] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d1_script
AIRFLOW_CTX_TASK_ID=insert_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-01-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-25T00:00:00+00:00
[2023-01-26 14:03:45,822] {logging_mixin.py:115} INFO - [INFO] GET DATA FROM MYSQL IS SUCCESSFUL
[2023-01-26 14:03:45,823] {logging_mixin.py:115} INFO - [INFO] TOTAL GETTING DATA TIME FROM MYSQL IS 0.07811999320983887 S
[2023-01-26 14:03:45,845] {logging_mixin.py:115} INFO - [INFO] GET DATA FROM MYSQL IS SUCCESSFUL
[2023-01-26 14:03:45,845] {logging_mixin.py:115} INFO - [INFO] TOTAL GETTING DATA TIME FROM MYSQL IS 0.022078990936279297 S
[2023-01-26 14:03:45,929] {logging_mixin.py:115} INFO - [INFO] INSERTED TO POSTGRES IS SUCCESSFUL
[2023-01-26 14:03:45,930] {logging_mixin.py:115} INFO - [INFO] TOTAL INSERTED TIME TO POSTGRES IS 0.03441309928894043 S
[2023-01-26 14:03:45,955] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/d1_script.py", line 104, in func_insert_province_daily
    transformer.create_province_daily()
  File "/opt/airflow/dags/modules/transformer.py", line 110, in create_province_daily
    data = data[['id', 'province_id', 'case_id', 'date', 'total']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['province_id'] not in index"
[2023-01-26 14:03:45,974] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=d1_script, task_id=insert_province_daily, execution_date=20230125T000000, start_date=20230126T140345, end_date=20230126T140345
[2023-01-26 14:03:45,987] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task insert_province_daily ("['province_id'] not in index"; 364)
[2023-01-26 14:03:46,024] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-26 14:03:46,062] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
